"""agentboot - a portable operating framework for long-running AI agent instances.

Five things live here, and they are one idea at five scales - everything is indexed by the SITUATION
that should trigger it, because the situation is the only thing an agent actually has:

* `boot` / `steps` / `status` - a tiered boot that **structurally cannot print a status line it
  did not earn**. A step reports success by returning evidence naming its source, never by
  asserting it, and every check must demonstrate that it is capable of failing.
* `enforcement` - the three hook layers that re-release orientation per session, per turn and per
  action, because doctrine read once at wake has decayed long before the failure it was meant to
  prevent.
* `tools` - a registry keyed by SITUATION rather than by name, which discovers what the
  environment offers and probes every claim before advertising it as reachable.
* `lessons` - the ledger of things learned the hard way, indexed by the TELL that recognises the
  situation, so a lesson fires before the mistake repeats instead of sitting in a file nobody opens.
* `minion` - lite agents that get doctrine and a bounded brief but not the stack; the brief is
  GENERATED by matching the errand against the ledger and the registry.
* `persona` - disposition as a MECHANISM, loaded at tier 2 before the agent learns what it can
  reach. What separates two agents holding identical doctrine is detection latency: one catches the
  mistake at step 0, the other is five steps past it and patches forward rather than unwinding.
* `keys` - the agent carries its own credentials as ciphertext and refuses to install any that
  cannot be fingerprinted, because a key that decrypts cleanly and has no fingerprint fails
  silently, hours later, looking like somebody else's problem.

Nothing in this package knows about any particular environment. Steps are whatever you make them.
"""
from .boot import Boot, Tier
from .curriculum import Curriculum, Module
from .enforcement import LAYERS, EnforcementInstaller, Layer
from .intake import Intake, Question
from .keys import Key, KeyFault, Keyring
from .lessons import Ledger, Lesson
from .minion import Errand, Minion
from .persona import Persona, Wardrobe
from .status import Status, StatusLine
from .steps import CommandStep, Evidence, FileStep, LazyStep, Result, Step, StepFailed
from .tools import Tool, ToolRegistry

__version__ = "0.2.0"

__all__ = [
    "LAYERS",
    "Boot",
    "CommandStep",
    "EnforcementInstaller",
    "Errand",
    "Curriculum",
    "Evidence",
    "Intake",
    "Module",
    "Question",
    "Key",
    "KeyFault",
    "Keyring",
    "FileStep",
    "Ledger",
    "Lesson",
    "Layer",
    "LazyStep",
    "Minion",
    "Persona",
    "Wardrobe",
    "Result",
    "Status",
    "StatusLine",
    "Step",
    "StepFailed",
    "Tier",
    "Tool",
    "ToolRegistry",
    "__version__",
]
